package org.opentollgate.android

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withTimeoutOrNull
import org.opentollgate.android.model.ConsumeEventView
import org.opentollgate.android.model.DetectedView
import org.opentollgate.android.model.DiscoveredPeer
import org.opentollgate.android.model.PaidView
import org.opentollgate.android.model.SEED_CANDIDATES
import org.opentollgate.android.model.TxKind
import org.opentollgate.android.model.UiState
import org.opentollgate.android.model.WalletState
import org.opentollgate.android.model.signalTier
import org.opentollgate.android.util.TokenResult
import org.opentollgate.android.util.buildLocalToken
import org.opentollgate.android.util.parseCashuToken
import org.opentollgate.android.util.stripScheme
// Generated by `just bindings` (uniffi-bindgen). Package = uniffi.<crate>.
import uniffi.tollgate_mobile.TollgateMobileNode

/**
 * Bridges the Compose UI to the native [TollgateMobileNode]. The node owns its
 * own tokio runtime + persisted identity (under filesDir), so all calls here are
 * synchronous FFI calls dispatched off the main thread via [viewModelScope].
 *
 * Session lifetime: [onPay] pays the bootstrap; on acceptance it calls
 * [startConsume], which records [UiState.sessionStartedAt] and then polls
 * [TollgateMobileNode.pollEvent] until the loop ends (stop / max_polls) — at
 * which point [UiState.sessionStartedAt] is cleared via a finally block.
 *
 * PENDING (ARCHITECTURE.md §6): the full SPA-mirror UI (Cashu mint/balance,
 * Lightning, QR scan, i18n) is built once the source-of-truth decision lands.
 * The detect/pay/consume plumbing below is already wired end to end.
 */
class TollgateViewModel(app: Application) : AndroidViewModel(app) {
    private val node: TollgateMobileNode = TollgateMobileNode(app.filesDir.absolutePath)
    private val wifiScanner = WifiTollGateScanner(app)

    private val _state = MutableStateFlow(
        UiState(
            ourPubkey = node.pubkeyHex(),
            // Identity is persisted under filesDir by the Rust core; surface the
            // path on Settings → Identity so a user can locate their keys. Version
            // + build hash are compile-time constants stamped by Gradle.
            dataDir = node.dataDir(),
            appVersion = BuildConfig.VERSION_NAME,
            buildHash = BuildConfig.GIT_HASH,
        ),
    )
    val state: StateFlow<UiState> = _state

    fun onHostChange(host: String) = _state.update { it.copy(baseHost = host) }
    fun onMintChange(mint: String) = _state.update { it.copy(mintUrl = mint) }
    fun onTokenChange(token: String) = _state.update { it.copy(paymentToken = token.trim().ifBlank { null }) }

    /** Set the bootstrap-token amount (sats). Clamped to ≥ 1. */
    fun onAmountChange(sat: Long) = _state.update { it.copy(amountSat = sat.coerceAtLeast(1L)) }

    /** Select an already-known mint as the active one (radio select on PayScreen). */
    fun onSelectMint(mint: String) = _state.update {
        if (mint == it.mintUrl) it else it.copy(mintUrl = mint)
    }

    /**
     * Add a user-entered mint URL to [UiState.knownMints] and select it.
     * Deduped; trailing slash and whitespace stripped. No URL-shape validation
     * here — the gateway is the arbiter of whether a mint is acceptable, and a
     * malformed URL surfaces as a [TollgateError.Network] on the next pay().
     */
    fun onAddMint(mint: String) {
        val trimmed = mint.trim().removeSuffix("/")
        if (trimmed.isEmpty()) return
        _state.update {
            val mints = (it.knownMints + trimmed).distinct()
            it.copy(knownMints = mints, mintUrl = trimmed)
        }
    }


    fun onDetect() = viewModelScope.launch(Dispatchers.IO) {
        _state.update { it.copy(error = null) }
        val host = state.value.baseHost
        // Try v1 HTTP first (production routers), fall back to v2 CBOR
        val v1Ad = V1GatewayClient.detect(host)
        if (v1Ad != null) {
            // Update known mints from the gateway's advertisement
            val gatewayMints = v1Ad.mints.filter { it.isNotBlank() }
            _state.update {
                val mints = (it.knownMints + gatewayMints).distinct()
                it.copy(
                    detected = DetectedView(
                        pubkeyHex = v1Ad.pubkeyHex,
                        unit = v1Ad.metric,
                        version = 1.toUByte(),
                        perUnit = v1Ad.pricePerStep,
                        perSecond = null,
                    ),
                    online = true,
                    knownMints = mints,
                    error = null,
                )
            }
        } else {
            // Fall back to v2 CBOR protocol
            runCatching { node.detect(host) }
                .onSuccess { d ->
                    _state.update {
                        it.copy(
                            detected = DetectedView(d.pubkeyHex, d.unit, d.version, d.price?.perUnit, d.price?.perSecond),
                            online = true,
                        )
                    }
                }
                .onFailure { e -> _state.update { it.copy(error = e.message ?: "detect failed", online = false) } }
        }
    }

    fun onPay(amountSat: Long = state.value.amountSat) = viewModelScope.launch(Dispatchers.IO) {
        _state.update { it.copy(paying = true, error = null) }
        try {
            val s = state.value
            // Try v1 HTTP first (production routers)
            val v1Ad = V1GatewayClient.detect(s.baseHost)
            if (v1Ad != null) {
                // V1 gateway: POST Cashu token directly
                val token = s.paymentToken
                if (token.isNullOrBlank()) {
                    _state.update { it.copy(error = "Paste a Cashu token from ${s.mintUrl} to pay") }
                    return@launch
                }
                val result = V1GatewayClient.pay(s.baseHost, token)
                _state.update {
                    it.copy(
                        paid = PaidView(v1Ad.pubkeyHex, result.accepted, v1Ad.pricePerStep),
                        error = result.error,
                    )
                }
                if (result.accepted) {
                    // V1 gateways manage access via the router firewall — no consume loop needed.
                    // Start a usage monitor instead.
                    _state.update { it.copy(sessionStartedAt = System.currentTimeMillis()) }
                }
            } else {
                // Fall back to v2 CBOR protocol
                runCatching { node.pay(s.baseHost, s.mintUrl, amountSat.toULong()) }
                    .onSuccess { p ->
                        _state.update { it.copy(paid = PaidView(p.peerPubkeyHex, p.accepted, p.price?.perUnit)) }
                        if (p.accepted) startConsume()
                    }
                    .onFailure { e -> _state.update { it.copy(error = e.message ?: "pay failed") } }
            }
        } finally {
            _state.update { it.copy(paying = false) }
        }
    }

    /**
     * Launch the background stay-online loop and record the session start time.
     * Wrapped in runCatching so a UniFFI-thrown TollgateError (e.g. "a consume
     * loop is already running") surfaces as [UiState.error] instead of crashing
     * the launched coroutine. The poll loop clears [UiState.sessionStartedAt] in
     * a finally block when it exits, so the uptime display always reflects the
     * real session state.
     */
    private fun startConsume() {
        val s = state.value
        runCatching {
            // UniFFI 0.28 maps u64 -> ULong, u32 -> UInt, u8 -> UByte. The literal
            // suffixes (uL/u) must match each parameter's FFI type exactly. Param
            // names are generated from the Rust snake_case (base_url -> baseUrl),
            // so they must be spelled exactly as the bindings declare them.
            node.startConsume(
                baseUrl = s.baseHost,
                mintUrl = s.mintUrl,
                amountSat = 21uL,
                topupSat = 5uL,
                intervalMs = 5000uL,
                maxPolls = null,
            )
        }.onSuccess {
            val startedAt = System.currentTimeMillis()
            _state.update { it.copy(sessionStartedAt = startedAt, error = null) }
            viewModelScope.launch(Dispatchers.IO) {
                try {
                    while (true) {
                        // pollEvent(timeoutMs: ULong) — returns null when the
                        // loop finished and the event queue is drained.
                        val ev = node.pollEvent(5000uL) ?: break
                        _state.update {
                            it.copy(
                                latest = ConsumeEventView(
                                    poll = ev.poll,
                                    remainingScaled = ev.remainingScaled,
                                    // ev.report?.delivered is ULong? (Rust u64);
                                    // down-cast to Long for the View (Long max ≈ 9 EB).
                                    delivered = ev.report?.delivered?.toLong(),
                                    cutOff = ev.cutOff,
                                    toppedUp = ev.toppedUp,
                                )
                            )
                        }
                    }
                } finally {
                    // Loop ended (stop_consume, max_polls, or thrown) → session over.
                    _state.update { it.copy(sessionStartedAt = null) }
                }
            }
        }.onFailure { e ->
            _state.update { it.copy(error = e.message ?: "start_consume failed") }
        }
    }

    fun onStop() {
        runCatching { node.stopConsume() }
        _state.update { it.copy(sessionStartedAt = null) }
    }

    // -------------------------------------------------------------------------
    // Discover — scan candidate gateways for nearby TollGate peers (Phase 1).
    // Probes the seed LAN-gateway list + the current baseHost + any user-added
    // candidates concurrently with detect(); Phase 2 (FIPS integration) replaces
    // this with a live mesh scan feeding the same DiscoveredPeer rows.
    // -------------------------------------------------------------------------

    /** Outstanding Discover scan (concurrent `detect()` probes). Held so a
     *  re-scan or [onStopDiscover] can cancel an in-flight sweep. */
    private var discoverJob: Job? = null

    /**
     * Probe every candidate gateway concurrently and publish the reachable
     * peers to [UiState.discovered], best-signal-first. Each `detect()` runs on
     * a [Dispatchers.IO] thread under a 3 s per-host cap, so a dead host never
     * stalls the sweep. Re-scanning cancels any in-flight job first.
     *
     * Note: the 3 s cap cancels the *await*, not the blocking `detect()` call
     * itself (FFI blocking calls are not interruptible by coroutine
     * cancellation). A silently-dropping host lingers on its IO thread until
     * the OS connect fails; for LAN gateway candidates this resolves in well
     * under a second (connection refused / host unreachable). A Rust-side probe
     * timeout is tracked as a Phase 2 follow-up. [onStopDiscover] cancels the
     * await so the UI stays responsive regardless.
     */
    fun onDiscover() {
        discoverJob?.cancel()
        discoverJob = viewModelScope.launch(Dispatchers.IO) {
            _state.update { it.copy(scanning = true, discoverError = null) }

            // Layer 1: WiFi SSID scan for TollGate-* networks
            val wifiResults = mutableListOf<String>()
            try {
                val cached = wifiScanner.getCachedResults()
                if (cached.isNotEmpty()) {
                    wifiResults.addAll(cached.map { it.displayName })
                }
                // Trigger fresh scan (async — results arrive via broadcast)
                wifiScanner.startScan { networks ->
                    val names = networks.map { it.displayName }
                    _state.update { it.copy(wifiNetworks = names) }
                }
                // Also check if currently connected to a TollGate SSID
                val connectedSsid = wifiScanner.getConnectedSsid()
                val dhcpGateway = wifiScanner.getConnectedGatewayUrl()
                if (connectedSsid != null && connectedSsid.startsWith("TollGate-", ignoreCase = true)) {
                    wifiResults.add(0, "CONNECTED: $connectedSsid")
                }
            } catch (e: Exception) {
                // WiFi scan failure is non-fatal — fall through to IP probe
            }
            if (wifiResults.isNotEmpty()) {
                _state.update { it.copy(wifiNetworks = wifiResults) }
            }

            try {
                val s = state.value
                // Include DHCP gateway if connected to a TollGate network
                val dhcpGateway = try { wifiScanner.getConnectedGatewayUrl() } catch (_: Exception) { null }
                val candidates = (SEED_CANDIDATES + s.extraCandidates + s.baseHost + listOfNotNull(dhcpGateway))
                    .map(String::trim)
                    .filter { it.isNotBlank() }
                    .distinct()
                val results = coroutineScope {
                    candidates.map { host -> async { probe(host) } }.awaitAll()
                }
                val sorted = results.sortedWith(
                    compareBy<DiscoveredPeer> { it.signal.ordinal }.thenBy { it.latencyMs },
                )
                _state.update { it.copy(discovered = sorted) }
            } catch (e: CancellationException) {
                // Re-scan or Stop cancelled the sweep; keep the existing list.
                throw e
            } catch (e: Exception) {
                _state.update { it.copy(discoverError = e.message ?: "scan failed") }
            } finally {
                _state.update { it.copy(scanning = false) }
            }
        }
    }

    /** Cancel an in-flight Discover scan (the Stop button). */
    fun onStopDiscover() {
        discoverJob?.cancel()
        discoverJob = null
        _state.update { it.copy(scanning = false) }
    }

    /**
     * Adopt a discovered peer as the active gateway: copy its base URL into
     * [UiState.baseHost] and pre-fill [UiState.detected] so PayScreen shows the
     * peer without a redundant Detect. TollGateApp then navigates to Pay.
     */
    fun onSelectPeer(peer: DiscoveredPeer) {
        _state.update {
            it.copy(
                baseHost = peer.baseUrl,
                detected = if (peer.reachable) {
                    DetectedView(
                        pubkeyHex = peer.pubkeyHex,
                        unit = peer.unit,
                        version = peer.version,
                        perUnit = peer.perUnit,
                        perSecond = peer.perSecond,
                    )
                } else {
                    it.detected
                },
                online = peer.reachable,
                error = null,
            )
        }
    }

    /** Add a user-entered gateway URL to the scan candidate set and re-scan. */
    fun onAddCandidate(host: String) {
        val normalized = host.trim().removeSuffix("/")
        if (normalized.isEmpty()) return
        _state.update { it.copy(extraCandidates = (it.extraCandidates + normalized).distinct()) }
        onDiscover()
    }

    /**
     * Probe one candidate. Tries v1 HTTP first (production routers on :2121),
     * falls back to v2 CBOR protocol. A network failure is reported as a
     * reachable=false peer rather than thrown, so the sweep continues.
     */
    private suspend fun probe(host: String): DiscoveredPeer {
        val started = System.currentTimeMillis()

        // Try v1 HTTP first
        val v1Ad = withTimeoutOrNull(4_000L) {
            V1GatewayClient.detect(host)
        }
        val latency = System.currentTimeMillis() - started

        if (v1Ad != null) {
            return DiscoveredPeer(
                baseUrl = host,
                pubkeyHex = v1Ad.pubkeyHex,
                reachable = true,
                latencyMs = latency,
                signal = signalTier(latency, reachable = true),
                unit = v1Ad.metric,
                version = 1.toUByte(),
                perUnit = v1Ad.pricePerStep,
                perSecond = null,
            )
        }

        // Fall back to v2 CBOR protocol
        val d = withTimeoutOrNull(3_000L) {
            runCatching { node.detect(host) }.getOrNull()
        }
        val latency2 = System.currentTimeMillis() - started

        return if (d != null) {
            DiscoveredPeer(
                baseUrl = host,
                pubkeyHex = d.pubkeyHex,
                reachable = true,
                latencyMs = latency2,
                signal = signalTier(latency2, reachable = true),
                unit = d.unit,
                version = d.version,
                perUnit = d.price?.perUnit,
                perSecond = d.price?.perSecond,
            )
        } else {
            DiscoveredPeer(
                baseUrl = host,
                pubkeyHex = "",
                reachable = false,
                latencyMs = 0L,
                signal = signalTier(0, reachable = false),
                unit = "",
                version = 0.toUByte(),
                perUnit = null,
                perSecond = null,
            )
        }
    }

    // -------------------------------------------------------------------------
    // Wallet — local Cashu model (Phase 1). Real NUT-03/05/06/07 integration
    // against a live mint is Phase 3 (master plan §Phase 3). See WalletState.
    // -------------------------------------------------------------------------

    /**
     * Receive (mint into the local wallet) by parsing a pasted/scanned cashu
     * token. Derives the token's face value from its proof sums and credits each
     * mint it draws on (a token may span multiple mints). Also feeds any new mint
     * into [UiState.knownMints] so PayScreen can select it. Parse failures
     * surface as [UiState.error] without mutating the wallet.
     */
    fun onReceiveToken(raw: String) {
        when (val result = parseCashuToken(raw)) {
            is TokenResult.Error -> _state.update { it.copy(error = result.reason) }
            is TokenResult.Ok -> {
                val token = result.token
                _state.update { s ->
                    var wallet = s.wallet
                    for (group in token.groups) {
                        wallet = wallet.applyTx(
                            mint = group.mint,
                            deltaSat = group.amountSat,
                            kind = TxKind.RECEIVE,
                            memo = token.memo ?: "received ${group.amountSat} sats",
                        )
                    }
                    // Register every mint the token drew on, so Pay/Status can use it.
                    val mints = (s.knownMints + token.groups.map { it.mint }).distinct()
                    s.copy(wallet = wallet, knownMints = mints, error = null)
                }
            }
        }
    }

    /**
     * Send (melt from the local wallet) [amountSat] of [mint] by minting a fresh
     * local token. Debits the mint's balance; on success stores the token as
     * [WalletState.lastSentToken] for WalletScreen to show + copy. Refuses when
     * the mint is unknown or the balance is insufficient (surfaced as error).
     *
     * The produced token is round-trippable by this app but is **not** spendable
     * at a real Cashu mint — real NUT-05 melt (settling at the mint) is Phase 3.
     */
    fun onSend(mint: String, amountSat: Long) {
        val normalized = mint.trim().removeSuffix("/")
        if (amountSat <= 0) {
            _state.update { it.copy(error = "amount must be positive") }
            return
        }
        _state.update { s ->
            val held = s.wallet.balanceOf(normalized)
            if (held < amountSat) {
                s.copy(error = "insufficient balance on ${stripScheme(normalized)} ($held < $amountSat)")
            } else {
                val token = buildLocalToken(normalized, amountSat, memo = "send $amountSat sats")
                val wallet = s.wallet
                    .applyTx(
                        mint = normalized,
                        deltaSat = -amountSat,
                        kind = TxKind.SEND,
                        memo = "sent $amountSat sats",
                    )
                    .copy(lastSentToken = token)
                s.copy(wallet = wallet, error = null)
            }
        }
    }

    /** Clear the last "Send" token banner on WalletScreen. */
    fun onDismissLastSent() = _state.update { it.copy(wallet = it.wallet.copy(lastSentToken = null)) }
}
