package org.opentollgate.android

import android.app.Application
import android.util.Log
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withTimeoutOrNull
import org.opentollgate.android.model.BalanceView
import org.opentollgate.android.model.ConsumeEventView
import org.opentollgate.android.model.DetectedView
import org.opentollgate.android.model.DiscoveredPeer
import org.opentollgate.android.model.PaidView
import org.opentollgate.android.model.SEED_CANDIDATES
import org.opentollgate.android.model.TxKind
import org.opentollgate.android.model.UiState
import org.opentollgate.android.model.WalletState
import org.opentollgate.android.model.signalTier
import org.opentollgate.android.util.TokenResult
import org.opentollgate.android.util.buildLocalToken
import org.opentollgate.android.util.parseCashuToken
import org.opentollgate.android.util.stripScheme
// Generated by `just bindings` (uniffi-bindgen). Package = uniffi.<crate>.
import uniffi.tollgate_mobile.TollgateMobileNode

/**
 * Bridges the Compose UI to the native [TollgateMobileNode]. The node owns its
 * own tokio runtime + persisted identity (under filesDir), so all calls here are
 * synchronous FFI calls dispatched off the main thread via [viewModelScope].
 *
 * Session lifetime: [onPay] pays the bootstrap; on acceptance it calls
 * [startConsume], which records [UiState.sessionStartedAt] and then polls
 * [TollgateMobileNode.pollEvent] until the loop ends (stop / max_polls) — at
 * which point [UiState.sessionStartedAt] is cleared via a finally block.
 *
 * PENDING (ARCHITECTURE.md §6): the full SPA-mirror UI (Cashu mint/balance,
 * Lightning, QR scan, i18n) is built once the source-of-truth decision lands.
 * The detect/pay/consume plumbing below is already wired end to end.
 */
class TollgateViewModel(app: Application) : AndroidViewModel(app) {
    private companion object {
        const val TAG = "TollgateViewModel"
    }
    val node: TollgateMobileNode = TollgateMobileNode(app.filesDir.absolutePath)
    private val wifiScanner = WifiTollGateScanner(app)
    val wifiConnector = WifiNetworkConnector(app)

    private val _state = MutableStateFlow(
        UiState(
            ourPubkey = node.pubkeyHex(),
            // Identity is persisted under filesDir by the Rust core; surface the
            // path on Settings → Identity so a user can locate their keys. Version
            // + build hash are compile-time constants stamped by Gradle.
            dataDir = node.dataDir(),
            appVersion = BuildConfig.VERSION_NAME,
            buildHash = BuildConfig.GIT_HASH,
        ),
    )
    val state: StateFlow<UiState> = _state

    init {
        // Pre-mint ecash from testnut on startup so the wallet is loaded
        // before the user connects to any tollgate.
        autoMintOnStartup()
    }

    /**
     * Auto-mint ecash tokens from testnut (auto-settles invoices in ~3s).
     * Runs in background on app launch. Stores token in wallet + sets as
     * paymentToken so it's ready to spend immediately.
     */
    private fun autoMintOnStartup() = viewModelScope.launch(Dispatchers.IO) {
        // Local FakeWallet mint — auto-settles Lightning invoices instantly.
        // No real Lightning payment needed. Use ethernet IP reachable from
        // both the phone (via tollgate WiFi) and the gateway itself.
        // Mint listens on 0.0.0.0:4444 — reachable from both WiFi (192.168.2.x)
        // and ethernet (10.230.237.x). Use WiFi IP since the phone is on home WiFi.
        val testMint = "http://192.168.2.33:4444"
        val amount = 21L // 21 sats — enough for several tollgate steps
        _state.update { it.copy(scanning = true) }
        try {
            Log.i(TAG, "autoMint: requesting $amount sats from $testMint…")
            val token = node.autoMint(testMint, amount.toULong(), 30uL)
            Log.i(TAG, "autoMint: success! token=${token.take(60)}…")
            // Parse token value for wallet state
            val tokenResult = parseCashuToken(token)
            val (mintForWallet, value) = when (tokenResult) {
                is TokenResult.Ok -> {
                    val t = tokenResult.token
                    (t.groups.firstOrNull()?.mint ?: testMint) to t.amountSat
                }
                is TokenResult.Error -> testMint to amount
            }
            _state.update {
                it.copy(
                    scanning = false,
                    paymentToken = token,
                    mintUrl = testMint,
                    wallet = it.wallet
                        .applyTx(mintForWallet, value, TxKind.RECEIVE, "Auto-minted $value sats from testnut"),
                    error = null,
                )
            }
            Log.i(TAG, "autoMint: wallet loaded with $value sats")
        } catch (e: Exception) {
            Log.e(TAG, "autoMint: failed — ${e.message}")
            _state.update { it.copy(scanning = false) }
            // Non-fatal — user can mint manually via Wallet screen
        }
    }

    fun onHostChange(host: String) = _state.update { it.copy(baseHost = host) }
    fun onMintChange(mint: String) = _state.update { it.copy(mintUrl = mint) }
    fun onTokenChange(token: String) = _state.update { it.copy(paymentToken = token) }

    // ── Cashu Minting Flow ─────────────────────────────────────────

    /** Polling job for checking Lightning payment status. */
    private var quotePollJob: Job? = null

    /**
     * Step 1: Request a Lightning invoice from the selected mint.
     * Called before connecting to TollGate WiFi (uses default internet).
     */
    fun onRequestInvoice() = viewModelScope.launch(Dispatchers.IO) {
        val mint = state.value.mintUrl
        val amount = state.value.amountSat.coerceAtLeast(1)

        _state.update {
            it.copy(
                mintingInvoice = true,
                error = null,
                mintedToken = null,
                mintInvoice = null,
                mintQuoteId = null,
            )
        }

        try {
            val quote = node.requestMintQuote(mint, amount.toULong())
            _state.update {
                it.copy(
                    mintingInvoice = false,
                    mintInvoice = quote.invoice,
                    mintQuoteId = quote.quoteId,
                    mintingWaiting = true,
                )
            }
            startQuotePolling(mint, quote.quoteId)
        } catch (e: Exception) {
            _state.update {
                it.copy(
                    mintingInvoice = false,
                    error = "Failed to get Lightning invoice from $mint: ${e.message}",
                )
            }
        }
    }

    /**
     * Step 2: Poll the mint every 5 seconds until the Lightning invoice is paid.
     */
    private fun startQuotePolling(mint: String, quoteId: String) {
        quotePollJob?.cancel()
        quotePollJob = viewModelScope.launch(Dispatchers.IO) {
            var attempts = 0
            val maxAttempts = 120 // 10 minutes max
            while (isActive && attempts < maxAttempts) {
                delay(5000)
                val quoteState = try {
                    node.checkMintQuote(mint, quoteId)
                } catch (_: Exception) { "UNPAID" }
                if (quoteState == "PAID") {
                    // Payment confirmed — mint the tokens
                    mintAfterPayment(mint, quoteId)
                    return@launch
                } else if (quoteState == "EXPIRED") {
                    _state.update {
                        it.copy(
                            mintingWaiting = false,
                            error = "Lightning invoice expired. Try again.",
                        )
                    }
                    return@launch
                }
                attempts++
            }
            // Timeout
            _state.update {
                it.copy(
                    mintingWaiting = false,
                    error = "Timed out waiting for payment. Try again.",
                )
            }
        }
    }

    /**
     * Step 3: Mint Cashu tokens after Lightning payment is confirmed.
     */
    private fun mintAfterPayment(mint: String, quoteId: String) {
        viewModelScope.launch(Dispatchers.IO) {
            _state.update { it.copy(mintingWaiting = false, mintingTokens = true) }

            val amount = state.value.amountSat
            try {
                val token = node.mintTokens(mint, quoteId, amount.toULong())
                _state.update {
                    it.copy(
                        mintingTokens = false,
                        mintedToken = token,
                        paymentToken = token,
                        error = null,
                    )
                }
            } catch (e: Exception) {
                _state.update {
                    it.copy(
                        mintingTokens = false,
                        error = "Failed to mint Cashu tokens: ${e.message}",
                    )
                }
            }
        }
    }

    /** Cancel any pending minting/polling. */
    fun onCancelMinting() {
        quotePollJob?.cancel()
        _state.update {
            it.copy(
                mintingInvoice = false,
                mintingWaiting = false,
                mintingTokens = false,
                mintInvoice = null,
                mintQuoteId = null,
            )
        }
    }

    /** Set the bootstrap-token amount (sats). Clamped to ≥ 1. */
    fun onAmountChange(sat: Long) = _state.update { it.copy(amountSat = sat.coerceAtLeast(1L)) }

    /** Select an already-known mint as the active one (radio select on PayScreen). */
    fun onSelectMint(mint: String) = _state.update {
        if (mint == it.mintUrl) it else it.copy(mintUrl = mint)
    }

    /**
     * Add a user-entered mint URL to [UiState.knownMints] and select it.
     * Deduped; trailing slash and whitespace stripped. No URL-shape validation
     * here — the gateway is the arbiter of whether a mint is acceptable, and a
     * malformed URL surfaces as a [TollgateError.Network] on the next pay().
     */
    fun onAddMint(mint: String) {
        val trimmed = mint.trim().removeSuffix("/")
        if (trimmed.isEmpty()) return
        _state.update {
            val mints = (it.knownMints + trimmed).distinct()
            it.copy(knownMints = mints, mintUrl = trimmed)
        }
    }


    fun onDetect() = viewModelScope.launch(Dispatchers.IO) {
        _state.update { it.copy(error = null) }
        val host = state.value.baseHost
        // Try v1 HTTP first (production routers), fall back to v2 CBOR
        // Pass active TollGate WiFi network for correct routing
        val net = wifiConnector.activeNetwork.value
        val v1Ad = V1GatewayClient.detect(host, net)
        if (v1Ad != null) {
            // Query device MAC and update all gateway state
            val mac = V1GatewayClient.getWhoami(host, net)
            val gatewayMints = v1Ad.mints.filter { it.isNotBlank() }
            // Merge gateway mints into known mints
            _state.update {
                val mergedMints = (it.knownMints + gatewayMints).distinct()
                val preferredMint = when {
                    gatewayMints.isEmpty() -> it.mintUrl
                    it.mintUrl in gatewayMints -> it.mintUrl
                    else -> gatewayMints.first()
                }
                it.copy(
                    detected = DetectedView(
                        pubkeyHex = v1Ad.pubkeyHex,
                        unit = v1Ad.metric,
                        version = 1.toUByte(),
                        perUnit = v1Ad.pricePerStep,
                        perSecond = null,
                    ),
                    online = true,
                    knownMints = mergedMints,
                    mintUrl = preferredMint,
                    gatewayMints = gatewayMints,
                    gatewayMac = mac,
                    error = null,
                )
            }
            // Query initial balance
            refreshGatewayBalance()
        } else {
            // Fall back to v2 CBOR protocol
            runCatching { node.detect(host) }
                .onSuccess { d ->
                    _state.update {
                        it.copy(
                            detected = DetectedView(d.pubkeyHex, d.unit, d.version, d.price?.perUnit, d.price?.perSecond),
                            online = true,
                        )
                    }
                }
                .onFailure { e -> _state.update { it.copy(error = e.message ?: "detect failed", online = false) } }
        }
    }

    /** Poll the gateway's /balance endpoint for live session telemetry. */
    private fun refreshGatewayBalance() {
        val host = state.value.baseHost
        viewModelScope.launch(Dispatchers.IO) {
            val bal = V1GatewayClient.getBalance(host, wifiConnector.activeNetwork.value)
            if (bal != null) {
                _state.update {
                    it.copy(
                        gatewayBalance = BalanceView(
                            sessionActive = bal.sessionActive,
                            metric = bal.metric,
                            usage = bal.usage,
                            allotment = bal.allotment,
                            remaining = bal.remaining,
                            startTime = bal.startTime,
                        )
                    )
                }
            }
        }
    }

    fun onPay(amountSat: Long = state.value.amountSat) = viewModelScope.launch(Dispatchers.IO) {
        _state.update { it.copy(paying = true, error = null) }
        try {
            val s = state.value

            // Use mintedToken from minting flow, or fall back to manually pasted token
            val token = s.mintedToken ?: s.paymentToken
            if (token.isNullOrBlank()) {
                _state.update { it.copy(error = "Mint tokens first (Get Invoice → pay Lightning → Mint), or paste a Cashu token manually") }
                return@launch
            }
            Log.i(TAG, "onPay: token=${token.take(40)}... gateway=${s.baseHost}")

            // Try v1 HTTP only (all production TollGate routers use :2121)
            val net = wifiConnector.activeNetwork.value
            Log.d(TAG, "onPay: activeNetwork=$net")
            val v1Ad = V1GatewayClient.detect(s.baseHost, net)
            if (v1Ad != null) {
                // V1 gateway: POST Cashu token directly
                Log.d(TAG, "onPay: gateway detected, posting token...")
                val result = V1GatewayClient.pay(s.baseHost, token, net)
                Log.i(TAG, "onPay: result accepted=${result.accepted} error=${result.error} body=${result.rawJson.take(200)}")
                
                if (result.accepted) {
                    _state.update {
                        it.copy(
                            paid = PaidView(v1Ad.pubkeyHex, true, v1Ad.pricePerStep),
                            error = null,
                            sessionStartedAt = System.currentTimeMillis(),
                        )
                    }
                    startBalanceMonitor()
                } else {
                    // Payment failed — extract the gateway's error code + message
                    val errMsg = result.error ?: extractGatewayError(result.rawJson)
                    // If token was spent, clear it so we mint fresh next time
                    val tokenSpent = errMsg.contains("spent", ignoreCase = true) ||
                        errMsg.contains("gate-open-failed", ignoreCase = true)
                    _state.update {
                        it.copy(
                            paid = PaidView(v1Ad.pubkeyHex, false, v1Ad.pricePerStep),
                            error = errMsg,
                            // Clear spent token so next pay mints fresh
                            mintedToken = if (tokenSpent) null else it.mintedToken,
                            paymentToken = if (tokenSpent) null else it.paymentToken,
                        )
                    }
                    // Auto-mint a fresh token after spend failure
                    if (tokenSpent) {
                        Log.i(TAG, "onPay: token consumed, auto-minting fresh token...")
                        autoMintOnStartup()
                    }
                }
            } else {
                // Gateway unreachable — phone is NOT on the TollGate WiFi
                _state.update {
                    it.copy(error = "Cannot reach gateway at ${s.baseHost}. " +
                        "Connect to a TollGate WiFi network first (Discover → Connect).")
                }
            }
        } catch (e: Exception) {
            _state.update { it.copy(error = e.message ?: "pay failed") }
        } finally {
            _state.update { it.copy(paying = false) }
        }
    }

    /**
     * Launch the background stay-online loop and record the session start time.
     * Wrapped in runCatching so a UniFFI-thrown TollgateError (e.g. "a consume
     * loop is already running") surfaces as [UiState.error] instead of crashing
     * the launched coroutine. The poll loop clears [UiState.sessionStartedAt] in
     * a finally block when it exits, so the uptime display always reflects the
     * real session state.
     */
    private fun startConsume() {
        val s = state.value
        runCatching {
            // UniFFI 0.28 maps u64 -> ULong, u32 -> UInt, u8 -> UByte. The literal
            // suffixes (uL/u) must match each parameter's FFI type exactly. Param
            // names are generated from the Rust snake_case (base_url -> baseUrl),
            // so they must be spelled exactly as the bindings declare them.
            node.startConsume(
                baseUrl = s.baseHost,
                mintUrl = s.mintUrl,
                amountSat = 21uL,
                topupSat = 5uL,
                intervalMs = 5000uL,
                maxPolls = null,
            )
        }.onSuccess {
            val startedAt = System.currentTimeMillis()
            _state.update { it.copy(sessionStartedAt = startedAt, error = null) }
            viewModelScope.launch(Dispatchers.IO) {
                try {
                    while (true) {
                        // pollEvent(timeoutMs: ULong) — returns null when the
                        // loop finished and the event queue is drained.
                        val ev = node.pollEvent(5000uL) ?: break
                        _state.update {
                            it.copy(
                                latest = ConsumeEventView(
                                    poll = ev.poll,
                                    remainingScaled = ev.remainingScaled,
                                    // ev.report?.delivered is ULong? (Rust u64);
                                    // down-cast to Long for the View (Long max ≈ 9 EB).
                                    delivered = ev.report?.delivered?.toLong(),
                                    cutOff = ev.cutOff,
                                    toppedUp = ev.toppedUp,
                                )
                            )
                        }
                    }
                } finally {
                    // Loop ended (stop_consume, max_polls, or thrown) → session over.
                    _state.update { it.copy(sessionStartedAt = null) }
                }
            }
        }.onFailure { e ->
            _state.update { it.copy(error = e.message ?: "start_consume failed") }
        }
    }

    /** Outstanding balance monitor job (v1 gateway /balance polling). */
    private var balanceJob: Job? = null

    /** Cancel the balance monitor (the Stop button or session end). */
    private fun stopBalanceMonitor() {
        balanceJob?.cancel()
        balanceJob = null
    }

    /**
     * Poll the gateway's /balance endpoint every 3 seconds for live session
     * telemetry (usage, remaining, session_active). Stops when the session
     * becomes inactive or the user cancels. Only used for v1 HTTP gateways —
     * v2 CBOR gateways use the consume loop's MeteringReport events.
     */
    private fun startBalanceMonitor() {
        stopBalanceMonitor()
        balanceJob = viewModelScope.launch(Dispatchers.IO) {
            try {
                while (true) {
                    val host = state.value.baseHost
                    val bal = V1GatewayClient.getBalance(host, wifiConnector.activeNetwork.value)
                    if (bal != null) {
                        _state.update {
                            it.copy(
                                gatewayBalance = BalanceView(
                                    sessionActive = bal.sessionActive,
                                    metric = bal.metric,
                                    usage = bal.usage,
                                    allotment = bal.allotment,
                                    remaining = bal.remaining,
                                    startTime = bal.startTime,
                                ),
                                // If session ended server-side, clear our session marker
                                sessionStartedAt = if (bal.sessionActive) it.sessionStartedAt else null,
                            )
                        }
                        if (!bal.sessionActive) break
                    }
                    kotlinx.coroutines.delay(3000L)
                }
            } catch (_: CancellationException) {
                // Stopped by user — keep the last known balance
            } finally {
                _state.update { it.copy(sessionStartedAt = null) }
            }
        }
    }

    fun onStop() {
        runCatching { node.stopConsume() }
        stopBalanceMonitor()
        _state.update { it.copy(sessionStartedAt = null) }
    }

    // -------------------------------------------------------------------------
    // Discover — scan candidate gateways for nearby TollGate peers (Phase 1).
    // Probes the seed LAN-gateway list + the current baseHost + any user-added
    // candidates concurrently with detect(); Phase 2 (FIPS integration) replaces
    // this with a live mesh scan feeding the same DiscoveredPeer rows.
    // -------------------------------------------------------------------------

    /** Outstanding Discover scan (concurrent `detect()` probes). Held so a
     *  re-scan or [onStopDiscover] can cancel an in-flight sweep. */
    private var discoverJob: Job? = null

    /**
     * Probe every candidate gateway concurrently and publish the reachable
     * peers to [UiState.discovered], best-signal-first. Each `detect()` runs on
     * a [Dispatchers.IO] thread under a 3 s per-host cap, so a dead host never
     * stalls the sweep. Re-scanning cancels any in-flight job first.
     *
     * Note: the 3 s cap cancels the *await*, not the blocking `detect()` call
     * itself (FFI blocking calls are not interruptible by coroutine
     * cancellation). A silently-dropping host lingers on its IO thread until
     * the OS connect fails; for LAN gateway candidates this resolves in well
     * under a second (connection refused / host unreachable). A Rust-side probe
     * timeout is tracked as a Phase 2 follow-up. [onStopDiscover] cancels the
     * await so the UI stays responsive regardless.
     */
    fun onDiscover() {
        discoverJob?.cancel()
        discoverJob = viewModelScope.launch(Dispatchers.IO) {
            _state.update { it.copy(scanning = true, discoverError = null) }

            // Layer 1: WiFi SSID scan for TollGate-* networks
            val wifiResults = mutableListOf<String>()
            try {
                val cached = wifiScanner.getCachedResults()
                if (cached.isNotEmpty()) {
                    wifiResults.addAll(cached.map { it.displayName })
                }
                // Trigger fresh scan (async — results arrive via broadcast)
                wifiScanner.startScan { networks ->
                    val names = networks.map { it.displayName }
                    _state.update { it.copy(wifiNetworks = names) }
                }
                // Also check if currently connected to a TollGate SSID
                val connectedSsid = wifiScanner.getConnectedSsid()
                val dhcpGateway = wifiScanner.getConnectedGatewayUrl()
                if (connectedSsid != null && connectedSsid.startsWith("TollGate-", ignoreCase = true)) {
                    wifiResults.add(0, "CONNECTED: $connectedSsid")
                }
            } catch (e: Exception) {
                // WiFi scan failure is non-fatal — fall through to IP probe
            }
            if (wifiResults.isNotEmpty()) {
                _state.update { it.copy(wifiNetworks = wifiResults) }
            }

            try {
                val s = state.value
                // Include gateway from active TollGate WiFi network (LinkProperties)
                // and DHCP fallback. Filter out invalid URLs (IPv6, empty host).
                val activeGw = try { wifiConnector.getGatewayUrl() } catch (_: Exception) { null }
                val dhcpGateway = try { wifiScanner.getConnectedGatewayUrl() } catch (_: Exception) { null }
                val candidates = (SEED_CANDIDATES + s.extraCandidates + s.baseHost + listOfNotNull(activeGw, dhcpGateway))
                    .map(String::trim)
                    .filter { it.isNotBlank() && !it.contains("::") && !it.contains("http://:") }
                    .distinct()
                val results = coroutineScope {
                    candidates.map { host -> async { probe(host) } }.awaitAll()
                }
                val sorted = results.sortedWith(
                    compareBy<DiscoveredPeer> { it.signal.ordinal }.thenBy { it.latencyMs },
                )
                _state.update { it.copy(discovered = sorted) }
            } catch (e: CancellationException) {
                // Re-scan or Stop cancelled the sweep; keep the existing list.
                throw e
            } catch (e: Exception) {
                _state.update { it.copy(discoverError = e.message ?: "scan failed") }
            } finally {
                _state.update { it.copy(scanning = false) }
            }
        }
    }

    /** Cancel an in-flight Discover scan (the Stop button). */
    fun onStopDiscover() {
        discoverJob?.cancel()
        discoverJob = null
        _state.update { it.copy(scanning = false) }
    }

    /**
     * Adopt a discovered peer as the active gateway: copy its base URL into
     * [UiState.baseHost] and pre-fill [UiState.detected] so PayScreen shows the
     * peer without a redundant Detect. TollGateApp then navigates to Pay.
     */
    fun onSelectPeer(peer: DiscoveredPeer) {
        _state.update {
            // Merge the gateway's accepted mints into knownMints so PayScreen
            // shows exactly what this router accepts (queried from GET /).
            val mergedMints = (it.knownMints + peer.acceptedMints).distinct()
            // Auto-select the first gateway-accepted mint if current selection
            // isn't in the gateway's list.
            val preferredMint = when {
                peer.acceptedMints.isEmpty() -> it.mintUrl
                it.mintUrl in peer.acceptedMints -> it.mintUrl
                else -> peer.acceptedMints.first()
            }
            it.copy(
                baseHost = peer.baseUrl,
                detected = if (peer.reachable) {
                    DetectedView(
                        pubkeyHex = peer.pubkeyHex,
                        unit = peer.unit,
                        version = peer.version,
                        perUnit = peer.perUnit,
                        perSecond = peer.perSecond,
                    )
                } else {
                    it.detected
                },
                online = peer.reachable,
                knownMints = mergedMints,
                mintUrl = preferredMint,
                error = null,
            )
        }
    }

    /** Add a user-entered gateway URL to the scan candidate set and re-scan. */
    fun onAddCandidate(host: String) {
        val normalized = host.trim().removeSuffix("/")
        if (normalized.isEmpty()) return
        _state.update { it.copy(extraCandidates = (it.extraCandidates + normalized).distinct()) }
        onDiscover()
    }

    /**
     * Connect to a TollGate WiFi SSID, then detect the gateway, then merge mints.
     *
     * Flow:
     * 1. WifiNetworkSpecifier → system dialog (user confirms)
     * 2. bindProcessToNetwork → HTTP traffic routes through TollGate WiFi
     * 3. Query DHCP gateway → probe :2121
     * 4. Parse advertisement → merge mints into knownMints
     * 5. Set baseHost + detected → auto-navigate to Pay screen
     *
     * @param ssid e.g. "TollGate-F794"
     */
    fun onConnectToWifi(ssid: String) = viewModelScope.launch(Dispatchers.IO) {
        _state.update { it.copy(scanning = true, error = null, discoverError = null) }

        // Step 1: Connect to the SSID
        val network = wifiConnector.connectToSsid(ssid)
        if (network == null) {
            _state.update {
                it.copy(
                    scanning = false,
                    error = "Could not connect to $ssid",
                )
            }
            return@launch
        }

        // Step 2: Wait for DHCP to settle, then probe multiple gateway candidates
        delay(2000) // DHCP needs time on some routers
        val candidates = wifiConnector.getGatewayCandidates(network)
        Log.i("TollgateViewModel", "Gateway candidates from TollGate WiFi: $candidates")
        
        if (candidates.isEmpty()) {
            _state.update {
                it.copy(
                    scanning = false,
                    error = "Connected to $ssid but couldn't determine gateway IP",
                )
            }
            return@launch
        }

        // Step 3: Probe ALL candidates in parallel — first responder wins
        val gatewayUrl = candidates.firstOrNull { url ->
            V1GatewayClient.detect(url, network) != null
        } ?: candidates.first() // fallback: try first even if none responded yet

        Log.i("TollgateViewModel", "Using gateway: $gatewayUrl")

        // Step 4: Detect the gateway
        val ad = V1GatewayClient.detect(gatewayUrl, network)
        if (ad == null) {
            _state.update {
                it.copy(
                    scanning = false,
                    baseHost = gatewayUrl,
                    error = "Connected to $ssid but gateway at $gatewayUrl didn't respond. Tried: ${candidates.joinToString()}",
                )
            }
            return@launch
        }

        // Step 4: Success — update all state
        val mac = V1GatewayClient.getWhoami(gatewayUrl, network)
        val gatewayMints = ad.mints.filter { it.isNotBlank() }
        val mergedMints = (state.value.knownMints + gatewayMints).distinct()
        val preferredMint = when {
            gatewayMints.isEmpty() -> state.value.mintUrl
            state.value.mintUrl in gatewayMints -> state.value.mintUrl
            else -> gatewayMints.first()
        }

        _state.update {
            it.copy(
                scanning = false,
                baseHost = gatewayUrl,
                detected = DetectedView(
                    pubkeyHex = ad.pubkeyHex,
                    unit = ad.metric,
                    version = 1.toUByte(),
                    perUnit = ad.pricePerStep,
                    perSecond = null,
                ),
                online = true,
                knownMints = mergedMints,
                mintUrl = preferredMint,
                gatewayMints = gatewayMints,
                gatewayMac = mac,
                discovered = listOf(
                    DiscoveredPeer(
                        baseUrl = gatewayUrl,
                        pubkeyHex = ad.pubkeyHex,
                        reachable = true,
                        latencyMs = 0L,
                        signal = org.opentollgate.android.model.SignalTier.STRONG,
                        unit = ad.metric,
                        version = 1.toUByte(),
                        perUnit = ad.pricePerStep,
                        perSecond = null,
                        acceptedMints = gatewayMints,
                        stepSize = ad.stepSize,
                    )
                ),
                error = null,
            )
        }

        // Query initial balance
        refreshGatewayBalance()
    }

    /**
     * Probe one candidate. Tries v1 HTTP first (production routers on :2121),
     * falls back to v2 CBOR protocol. A network failure is reported as a
     * reachable=false peer rather than thrown, so the sweep continues.
     */
    private suspend fun probe(host: String): DiscoveredPeer {
        val started = System.currentTimeMillis()

        // Try v1 HTTP first — pass active TollGate WiFi network
        val net = wifiConnector.activeNetwork.value
        val v1Ad = withTimeoutOrNull(4_000L) {
            V1GatewayClient.detect(host, net)
        }
        val latency = System.currentTimeMillis() - started

        if (v1Ad != null) {
            return DiscoveredPeer(
                baseUrl = host,
                pubkeyHex = v1Ad.pubkeyHex,
                reachable = true,
                latencyMs = latency,
                signal = signalTier(latency, reachable = true),
                unit = v1Ad.metric,
                version = 1.toUByte(),
                perUnit = v1Ad.pricePerStep,
                perSecond = null,
                acceptedMints = v1Ad.mints,
                stepSize = v1Ad.stepSize,
            )
        }

        // Fall back to v2 CBOR protocol
        val d = withTimeoutOrNull(3_000L) {
            runCatching { node.detect(host) }.getOrNull()
        }
        val latency2 = System.currentTimeMillis() - started

        return if (d != null) {
            DiscoveredPeer(
                baseUrl = host,
                pubkeyHex = d.pubkeyHex,
                reachable = true,
                latencyMs = latency2,
                signal = signalTier(latency2, reachable = true),
                unit = d.unit,
                version = d.version,
                perUnit = d.price?.perUnit,
                perSecond = d.price?.perSecond,
            )
        } else {
            DiscoveredPeer(
                baseUrl = host,
                pubkeyHex = "",
                reachable = false,
                latencyMs = 0L,
                signal = signalTier(0, reachable = false),
                unit = "",
                version = 0.toUByte(),
                perUnit = null,
                perSecond = null,
            )
        }
    }

    // -------------------------------------------------------------------------
    // Wallet — local Cashu model (Phase 1). Real NUT-03/05/06/07 integration
    // against a live mint is Phase 3 (master plan §Phase 3). See WalletState.
    // -------------------------------------------------------------------------

    /**
     * Receive (mint into the local wallet) by parsing a pasted/scanned cashu
     * token. Derives the token's face value from its proof sums and credits each
     * mint it draws on (a token may span multiple mints). Also feeds any new mint
     * into [UiState.knownMints] so PayScreen can select it. Parse failures
     * surface as [UiState.error] without mutating the wallet.
     */
    fun onReceiveToken(raw: String) {
        when (val result = parseCashuToken(raw)) {
            is TokenResult.Error -> _state.update { it.copy(error = result.reason) }
            is TokenResult.Ok -> {
                val token = result.token
                _state.update { s ->
                    var wallet = s.wallet
                    for (group in token.groups) {
                        wallet = wallet.applyTx(
                            mint = group.mint,
                            deltaSat = group.amountSat,
                            kind = TxKind.RECEIVE,
                            memo = token.memo ?: "received ${group.amountSat} sats",
                        )
                    }
                    // Register every mint the token drew on, so Pay/Status can use it.
                    val mints = (s.knownMints + token.groups.map { it.mint }).distinct()
                    s.copy(wallet = wallet, knownMints = mints, error = null)
                }
            }
        }
    }

    /**
     * Send (melt from the local wallet) [amountSat] of [mint] by minting a fresh
     * local token. Debits the mint's balance; on success stores the token as
     * [WalletState.lastSentToken] for WalletScreen to show + copy. Refuses when
     * the mint is unknown or the balance is insufficient (surfaced as error).
     *
     * The produced token is round-trippable by this app but is **not** spendable
     * at a real Cashu mint — real NUT-05 melt (settling at the mint) is Phase 3.
     */
    fun onSend(mint: String, amountSat: Long) {
        val normalized = mint.trim().removeSuffix("/")
        if (amountSat <= 0) {
            _state.update { it.copy(error = "amount must be positive") }
            return
        }
        _state.update { s ->
            val held = s.wallet.balanceOf(normalized)
            if (held < amountSat) {
                s.copy(error = "insufficient balance on ${stripScheme(normalized)} ($held < $amountSat)")
            } else {
                val token = buildLocalToken(normalized, amountSat, memo = "send $amountSat sats")
                val wallet = s.wallet
                    .applyTx(
                        mint = normalized,
                        deltaSat = -amountSat,
                        kind = TxKind.SEND,
                        memo = "sent $amountSat sats",
                    )
                    .copy(lastSentToken = token)
                s.copy(wallet = wallet, error = null)
            }
        }
    }

    /** Clear the last "Send" token banner on WalletScreen. */
    fun onDismissLastSent() = _state.update { it.copy(wallet = it.wallet.copy(lastSentToken = null)) }

    /** Extract human-readable error from gateway JSON response. */
    private fun extractGatewayError(json: String): String {
        return try {
            val obj = org.json.JSONObject(json)
            val tags = obj.optJSONArray("tags") ?: return obj.optString("content", "payment failed")
            var code: String? = null
            for (i in 0 until tags.length()) {
                val tag = tags.optJSONArray(i) ?: continue
                if (tag.optString(0) == "code") code = tag.optString(1)
            }
            val content = obj.optString("content", "")
            when (code) {
                "payment-error-token-spent" -> "Token already spent — minting fresh tokens..."
                "gate-open-failed" -> "Gateway verified payment but failed to open gate: $content"
                "payment-processing-failed" -> "Payment processing failed: $content"
                else -> content.ifBlank { code ?: "payment failed" }
            }
        } catch (_: Exception) {
            "payment failed"
        }
    }
}
